### ISSUE TITLE
与MineMention一起使用时不显示弹幕

### ISSUE THREAD

**Issue by TunYuntuwuQWQ** [LNatit/BulletChat#1]
环境:
minecraft 1.20.1
forge 47.2.20

bchat 1.2.11
Minemention 1.20.1-3.0.1  [相关链接](https://www.mcmod.cn/class/8545.html)
LibX 1.20.1-5.0.12  [相关链接](https://www.mcmod.cn/class/3207.html)

表现为以上mod共同安装时聊天栏发送任何消息均不以弹幕形式显示

**Comment by LNatit** [comment]
可否上传一下问题出现时候的游戏日志？
路径在对应游戏文件夹下 logs 文件夹内。
把里面的 debug.log 上传上来，或者传到 pastebin 网站然后贴链接

**Comment by TunYuntuwuQWQ** [comment]
没看着debug.log，只有个latest.log
https://mclo.gs/2wIw9ST

**Comment by LNatit** [comment]
我的失误，没有将最新版本上传到curseforge，请先到[这里](https://www.mcmod.cn/download/10965.html)下载最新版本的弹幕聊天（bchat-2.2.5-pure）替换掉老版本的文件
最新版里面黑名单改为了高级设置，如果你在老版本有添加黑名单的话请将黑名单里的内容复制进 _config/bchat-advanced.json_ 里，然后在文件里修改 _chatRegCustomized_ 条目为：
`"chatRegCustomized": "^<(?<sender>\\w{3,16})> (?<msg>.*$)"`
然后就应该可以正常显示了
如果以后还出现类似问题都可以靠修改这里的正则表达式解决

**Comment by LNatit** [comment]
我想写一篇关于此类问题的教程发布到mcmod上，你能接受教程配图中出现你的id和头像吗？

**Comment by TunYuntuwuQWQ** [comment]
感谢,正常发送消息可以显示了,但是"tellRegCustomized"应该怎么修改呢? https://mclo.gs/PYNibkT (完全不懂正则表达式)
我完全接受配图中出现我的id和头像
(顺便吐槽一下百科的下载页面我感觉我这辈子都没点过几次)

**Comment by LNatit** [comment]
坏了，我发现上面那个多重匹配表达式有误，待我修改一下（
tell的话我刚刚测试了一下，应该改成
`^(?<sender>\\w{3,16})悄悄地对你说：(?<msg>.*$)`
但是如果不打开设置里面的 _解析tell命令_ （默认关闭）的话这个正则其实是没有影响的

**Comment by TunYuntuwuQWQ** [comment]
再次感谢,我的问题已经全部解决了❤

**Comment by LNatit** [comment]
Java自带的正则库不支持捕获组重名，所以只能用这种容易出错的写法定义多种规则情况下的正则了
`"^(?:<|)(?<sender>\\w{3,16})(?:>|:) (?<msg>.*$)"`
这样定义的正则是会匹配聊天栏中类似
_<Player: hello
Player> hello_
的文本的，目前还没有想到什么很好的办法解决这个问题😥
