### ISSUE TITLE
当实际加载mod数量达到344后不再显示弹幕..

### ISSUE THREAD

**Issue by TunYuntuwuQWQ** [LNatit/BulletChat#2]
我很难用我已有的知识体系描述这个问题...
我测试了大概一整天每次测试的结果都不一样..
(在mod数为343时加入任意mod都会让弹幕失效,除mods以外没有任何文件变动)
最后我把问题锁定在了mod数量上面,,
为了验证我的猜想,,我用构建了一份forge47.2.20-mdk的examplemod
然后在mod数为343时加入游戏,弹幕还是正常显示的
然后我把examplemod-1.0.0.jar塞进了mods文件夹,启动!
弹幕没了.....
我还是不死心,我把examplemod多余的代码都删掉只剩下了↓
[图床链接](https://gitcode.net/TunYuntuwuQWQ/pic/uploads/7d3c408a32f24a35f7120ccd0a21d1c8/PixPin_2024-03-19_02-40-22.png)
然后重新构建了一份替换掉原本的examplemod-1.0.0.jar
弹幕还是没有,,,
再去掉看看————弹幕又出来了..
然后我尝试了丢几个.disabled的mod进去(被启动器禁用了的)
在实际加载343个mod,mods文件夹有350个文件时(7个已禁用mod)
弹幕依然是正常显示的,,
问题测试到现在我已经无法用我已有的知识来探究了(物理学不存在了!!),
我对344这个数字也没有其他的头绪了,
于是我只好把这个我认为抽象的问题提到这篇issue里,,
希望或许你对此有一点头绪..
[附上日志](https://mclo.gs/7Jcv55a)

**Comment by TunYuntuwuQWQ** [comment]
我注意到日志里显示的已加载mod是342个,也许我应该写「加载mod达到342时不显示弹幕」，但是我也很难找到那俩没出现在日志里的mod是谁,或许对「342」这个数字有点头绪也好..

**Comment by LNatit** [comment]
我看你用的启动器是HMCL，麻烦在版本对应的 **游戏设置** 里选中 **启用游戏特定设置** ，滑到最下面点击 **修改高级设置** ，进入高级设置界面后**往下滑**有一个 **Java虚拟机参数** 文本框，在框内添加以下文本（如果框内已经有其他文本则用空格分隔）
`-Dforge.logging.console.level=debug`
然后麻烦再次跑一遍游戏，正常测试，最后把游戏日志文件夹里的 _debug.log_ 传上来
_Tips: 无论是做包还是反馈issue，调试日志都比一般日志包含更多信息，一般来说更有用一些_ ❤

**Comment by LNatit** [comment]
以及，虽然现在没有看到具体的调试日志，但是类似的情况可能是由于游戏没有达到弹幕聊天的最低fps限制所引起的，你可以尝试在弹幕聊天的配置界面中把**最低帧率**拉低，**最多同屏弹幕数**适当拉高，然后再试试问题是否仍然存在

**Comment by TunYuntuwuQWQ** [comment]
不知道为什么,加了你说的参数之后仍然没有生成debug.log文件,,
但是我又不想让你什么都没法看,所以
我去找了一份debug参数加进去了..
(-Dlog4j2.formatMsgNoLookups=false -Dforge.logging.marker.networking=ACCEPT -Dforge.logging.marker.classloading=ACCEPT -Dforge.logging.marker.launchplugin=ACCEPT -Dforge.logging.marker.classdump=ACCEPT -Dforge.logging.marker.axform=ACCEPT -Dforge.logging.marker.eventbus=ACCEPT -Dforge.logging.marker.distxform=ACCEPT -Dforge.logging.marker.scan=ACCEPT -Dforge.logging.marker.registries=ACCEPT -Dforge.logging.marker.registrydump=ACCEPT -Dforge.logging.marker.splash=ACCEPT -Dforge.logging.marker.resource.cache=ACCEPT -Dforge.logging.mojang.level=ALL -Dforge.logging.classtransformer.level=ALL -Dforge.logging.console.level=ALL -Dforge.logging.file.level=ALL -Dforge.logging.debugFile.level=ALL)
然后跑了一份日志出来,
[大到我只能这么发了](https://www.wenshushu.cn/f/dnw624h2zrl)

另外,我尝试了你说的拉低最低帧率调高最多同屏弹幕数,问题仍然没有解决.


感谢您的耐心回复

**Comment by LNatit** [comment]
从log里看问题是聊天格式被其他mod修改了，在每条消息前面都添加了时间戳
你尝试一下把正则表达式修改成下面这样看看弹幕是不是正常了
`^\\[(?:[0-1]?[0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])] <(?<sender>\\w{4,16})> (?<msg>.*$)`
（tell如果也不行的话同理，在 _^_ 后面添加以下内容，注意有个空格）
`\\[(?:[0-1]?[0-9]|2[0-3]):(?:[0-5][0-9]):(?:[0-5][0-9])] `

**Comment by LNatit** [comment]
或者不想太麻烦的话把开头的 _^_ 去掉应该也能达到同样的效果

**Comment by LNatit** [comment]
以及我的建议是如果后面还想加mod的话弹幕聊天再遇到问题可以先放一放，到时候基本完工了一股脑全丢过来就行（
~~毕竟很多mod都喜欢对原版聊天系统动刀子~~
不过其实问题还是没有解决，我不能确定为什么mod数量达到344以后聊天消息会有时间戳

**Comment by TunYuntuwuQWQ** [comment]
时间戳是[wwta](https://www.mcmod.cn/class/3467.html)的功能,
而且我上次提问minemention时就已经安装测试过wwta与bchat的兼容性了
包括在mod数量为343时wwta也包含在内的,并且弹幕正常显示
我刚才也尝试了如你所说更改配置文件的正则表达式,
问题并没有解决~

其实我觉得这个问题是我遇到过最玄学的,
实在没有头绪的话也没关系,
我就尽量让整合包mod小于344就行了
(真的喜欢弹幕聊天这个小功能)


感谢您的耐心回复

**Comment by LNatit** [comment]
能发一个正常工作时候的log么🤔

**Comment by TunYuntuwuQWQ** [comment]
[这里](https://f.ws59.cn/f/dnwwhumchhs)

**Comment by LNatit** [comment]
挺怪的，我本地复现不出来
使用的是[这个脚本](https://paste.ee/p/v5bIp)生成350个空mod放入游戏中运行
我构建了一个测试版本，
[bchat-2.2.5-pure.jar.zip](https://github.com/LNatit/BulletChat/files/14646677/bchat-2.2.5-pure.jar.zip)
把所有的log的可见等级都调成info了（不需要再加一堆参数生成一个超大的log文件了）然后还添加了一些log方便诊断
您如果有空可以试着用这个版本跑两个正常和不正常的log给我，顺便再传一下你的两个配置文件吧

**Comment by LNatit** [comment]
Event priority issue, fix with commit [7feb7b](https://github.com/LNatit/BulletChat/commit/7feb7b797bb4e961dfe30ce48e7a7f0a7eb7d356).
